# Generated by Django 6.1.1 on 2026-09-27 23:28

import django.db.models.deletion
import ipam.fields
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0144_customfield_status'),
        ('ipam', '0097_merge_ipaddress_host_index_and_multi_protocol_services'),
        ('tenancy', '0027_fix_ltree_cascade_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProvisioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('customer_name', models.CharField(max_length=100, unique=True)),
                ('prefix', ipam.fields.IPNetworkField()),
                ('segment_count', models.PositiveSmallIntegerField(default=6)),
                ('segment_plan', models.JSONField(blank=True, default=list)),
                ('create_unused', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', editable=False, max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.tenant')),
                ('vrf', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.vrf')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ('customer_name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
